### PR TITLE
RAPID3 task

### PR DESCRIPTION
**Pull request by martinburchell**
### Checklist for new tasks:

- [X] Add task to relevant menus
- [X] Generate code documentation
- [X] Run self_test on server
- [X] Update docs/source/changelog.rst
- [X] Test documentation rebuilds without errors
- [X] If the text of the task cannot be submitted here for copyright reasons, there is a template XML file under `server/camcops_server/extra_string_templates`.

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by RudolfCardinal** [comment]
I've merged in from task-scheduler-dev/basdai-dev (and fixed a database script problem that Alembic sometimes generates, where it converts a generic string field to a MySQL-specific thing when you read back from a MySQL database), but I can't see a rapid3.rst so don't have the original task reference to check against; would you mind adding that, please? Apologies if I've missed it!

**Comment by martinburchell** [comment]
I'll aim to do the documentation today and then I'll move this PR out of draft status.

**Comment by martinburchell** [comment]
@RudolfCardinal now documented.

A couple of points:

I've used https://www.rheumatology.org/Portals/0/Files/RAPID3%20Form.pdf as a template, which has 0.5 granularity on the scales. The 2009 paper doesn't include the questions but refers to the 1999 MDHAQ, which RAPID3 i based on. This includes "mark the line" scales.

There seems to be some variation as to whether to use the raw 0-30 RAPID3 score as the final measure or whether to divide by 3 to get a 0-10 score (for comparison with other RAPID indices). At the moment, we're keeping the score 0-30.

Any thoughts?

**Comment by RudolfCardinal** [comment]
Looks good! Trivial tweaks only (mainly explanatory notes about the slightly odd scoring system).

**Pull request merged**
