### PR TITLE
Simplified spreadsheet export

### PR DESCRIPTION
**Pull request by RudolfCardinal**
Addresses https://github.com/RudolfCardinal/camcops/issues/228.

### CODE REVIEW

**Comment by RudolfCardinal** [comment]
Failing on numpy safety checks. One affects "all version", though (">0") -- not fixable, therefore disable this safety check? Its concern is https://github.com/numpy/numpy/issues/19038. Adding "--ignore 44715" might fix this (not sure where it goes) -- could do that for a few others too, or move the minimum Python version to 3.8 as numpy 1.22.0 isn't available for 3.7.

**Comment by martinburchell** [comment]
> Failing on numpy safety checks. One affects "all version", though (">0") -- not fixable, therefore disable this safety check? Its concern is [numpy/numpy#19038](https://github.com/numpy/numpy/issues/19038). Adding "--ignore 44715" might fix this (not sure where it goes) -- could do that for a few others too, or move the minimum Python version to 3.8 as numpy 1.22.0 isn't available for 3.7.

I'd do what I did for CRATE and stick with 3.7 and numpy 1.21. The ignores go in https://github.com/RudolfCardinal/camcops/blob/simplified_spreadsheet_export/.github/workflows/push-to-repository.yml#L59

We may find some of the warnings go away on Tuesday when the vulnerability database is updated.

**Comment by RudolfCardinal** [comment]
Thanks; trying again...

**Review by martinburchell — COMMENTED** [review]
It looks good from a code review perspective. I haven't tried it out yet. 

There's a dependency conflict in my virtualenv `kombu 5.2.3 has requirement amqp<6.0.0,>=5.0.9, but you have amqp 5.0.6.` and I need to check if that is just my stale environment. I'll look into the build failures also.

**Comment by RudolfCardinal** [comment]
I have kombu==5.2.2 -- it's not in setup.py, so I guess we should pin that (but do feel free to bump everything to your higher versions!).

**Comment by martinburchell** [comment]
> I have kombu==5.2.2 -- it's not in setup.py, so I guess we should pin that (but do feel free to bump everything to your higher versions!).

I rebuilt my virtualenv with the latest pip and now I don't have any broken dependencies

**Comment by martinburchell** [comment]
Good to merge from my point of view. I did a quick test and it seems to be working as expected.

**Comment by RudolfCardinal** [comment]
Thanks!

**Pull request merged**
